sudo: required

services: 
  - docker

before_install: 
  - docker build -t kyrieworkhard/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run kyrieworkhard/react-test npm test -- --coverage

after_success: 
  - docker build -t kyrieworkhard/multi-client ./client
  - docker build -t kyrieworkhard/multi-nginx ./nginx
  - docker build -t kyrieworkhard/multi-server ./server
  - docker build -t kyrieworkhard/multi-worker ./worker

#log us in to docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push kyrieworkhard/multi-client
  - docker push kyrieworkhard/multi-nginx
  - docker push kyrieworkhard/multi-server
  - docker push kyrieworkhard/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-487018625579
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
